applicationVersion: 1.1.0
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
  redis:
    host: localhost
    port: 6379
#    password: secret      # don't need this password arg

server:
  servlet:
    session:
      timeout:
        web: 86400
        mobile: -1

examportal:
  rememberme:
    timeout: 1209600
swagger enabled: true
#Logback logging
Logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss:SSS} %magenta([%thread}) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    root : INFO
    com.examportal.metrics.v1: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR