applicationVersion: 1.1.0
spring:
  datasource:
    url: jdbc:mysql://localhost/USERREALM
    username: root
    password: 1230
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 30000
    maxActive: 10
    maxIdle: 5
    removeAbandonedTimeout: 60
    removeAbandoned: false
    minEvictableIdleTimeMillis: 30000
  jpa:
    ddl-auto: update
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect